### ISSUE TITLE
channel closed error in cluster mode

### ISSUE THREAD

**Issue by carlisliu** [JerryC8080/Memeye#18]
When starting an app in cluster mode using pm2( pm2 start app_file -i 16), it keeps showing channel closed error in pm2 log file.
`
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:562:16)
    at Timeout.that.interval.setInterval (/var/www/node/express/node_modules/memeye/src/lib/Collector.js:57:24)
    at Timeout._onTimeout (/var/www/node/express/node_modules/async-listener/glue.js:188:31)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
`

**Comment by JerryC8080** [comment]
@carlisliu  
Hi, thanks for your feedback.
But i am so sorry to tell you that Memeye does not support multiple process on the way like pm2 yet.
Cause the dashboard that you seen on `http://localhost:23333` are designed to show state of one NodeJS process .
If want to collecting and showing multiple process's state, the first thing to do is extend dashboard to support multiple process showing.
And then to change the API of Memeye, that means the simple way we used Memeye now will be changed.
I considering how to support multiple process in the elegant way.
