### ISSUE TITLE
集成时出现错误

### ISSUE THREAD

**Issue by cubemoon** [JerryC8080/Memeye#20]
## 集成时出现错误
`node --debug-brk=28769 --nolazy majiang_server\app.js 
Debugger listening on port 28769
[Memeye] Memeye seting up...... 
Error: listen EADDRINUSE :::28769
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Agent.Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Agent.Server.listen (net.js:1385:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:86:44)
    at node.js:449:3
`
![Uploading QQ截图20170330100205.png…]()

**Comment by JerryC8080** [comment]
图挂了......

**Comment by carlisliu** [comment]
Error: listen EADDRINUSE :::28769 ，这不端口被占用了吗

**Comment by cubemoon** [comment]
@carlisliu thanks。
